version: "3.7"
services:
  db:
    container_name: "db"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: 'redis:latest'
    ports:
      - '127.0.0.1:5393:6379/tcp'
    volumes:
      - ./app/conf.d:/etc/redis/conf.rw
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'

  app:
    build:
      context: .
    env_file:
      - .env
    image: fastapi_app
    container_name: "fastapi_app"
    ports:
      - "2556:8000"
    depends_on:
      - db
      - redis

  nginx:
    container_name: "nginx"
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
