#version: "3.0"
#services:
#  db_test:
#    container_name: "db_test"
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_DB: ${TEST_DB_NAME}
#      POSTGRES_USER: ${TEST_DB_USER}
#      POSTGRES_PASSWORD: ${TEST_DB_PASS}
#      POSTGRES_HOST_AUTH_METHOD: trust
#    ports:
#      - "${TEST_DB_PORT}:5432"
#
#  redis:
#    container_name: redis
#    image: redis:latest
#    ports:
#      - "${TEST_REDIS_PORT}:6379"
#    volumes:
#      - ./pgdata:/var/lib/redis/data
#    restart: always
