version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./pgdata:/var/lib/redis/data
    restart: always